#!/bin/sh

set -eu

PREREQ=""

prereqs() {
  echo "$PREREQ"
}

case "${1:-}" in
  prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/sbin/e2fsck /usr/sbin/e2fsck
copy_exec /usr/sbin/resize2fs /usr/sbin/resize2fs
copy_exec /usr/sbin/mke2fs /usr/sbin/mke2fs
copy_exec /usr/sbin/parted /usr/sbin/parted
copy_exec /usr/sbin/partprobe /usr/sbin/partprobe
copy_exec /usr/bin/lsblk /usr/bin/lsblk
copy_exec /usr/bin/udevadm /usr/bin/udevadm
