#include "core/retroarch_input.h"

#include <filesystem>
#include <fstream>
#include <sstream>

namespace gb::core {
namespace {

std::string EscapeConfigValue(const std::string& value) {
  std::string out;
  out.reserve(value.size());
  for (const char c : value) {
    if (c == '\\' || c == '"') {
      out.push_back('\\');
    }
    if (c != '\n' && c != '\r') {
      out.push_back(c);
    }
  }
  return out;
}

bool ParseBinding(const std::string& encoded,
                  std::string& field_suffix,
                  std::string& value) {
  const auto colon = encoded.find(':');
  if (colon == std::string::npos || colon == 0 || colon + 1 >= encoded.size()) {
    return false;
  }
  const std::string kind = encoded.substr(0, colon);
  value = encoded.substr(colon + 1);
  if (kind == "key") {
    field_suffix.clear();
  } else if (kind == "btn") {
    field_suffix = "_btn";
  } else if (kind == "axis") {
    field_suffix = "_axis";
  } else {
    return false;
  }
  return !value.empty();
}

}  // namespace

std::string BuildRetroArchInputConfig(
    const std::string& device_name,
    const std::vector<std::pair<std::string, std::string>>& bindings,
    const int joypad_index) {
  std::ostringstream out;
  out << "# Generated by GameBird Shell. Changes are replaced when input settings "
         "are saved.\n";
  out << "# Active device: " << EscapeConfigValue(device_name) << "\n";
  if (joypad_index >= 0) {
    out << "input_player1_joypad_index = \"" << joypad_index << "\"\n";
  }
  for (const auto& [control, encoded] : bindings) {
    if (control.empty() || encoded.empty()) {
      continue;
    }
    std::string suffix;
    std::string value;
    if (!ParseBinding(encoded, suffix, value)) {
      continue;
    }

    const std::string prefix = "input_player1_" + control;
    // Clear the other binding types so a generated mapping cannot trigger both
    // the keyboard and joypad paths inherited from retroarch.cfg.
    out << prefix << " = \"nul\"\n";
    out << prefix << "_btn = \"nul\"\n";
    out << prefix << "_axis = \"nul\"\n";
    out << prefix << suffix << " = \"" << EscapeConfigValue(value) << "\"\n";
  }
  return out.str();
}

bool WriteRetroArchInputConfig(
    const std::string& path,
    const std::string& device_name,
    const std::vector<std::pair<std::string, std::string>>& bindings,
    const int joypad_index,
    std::string& error) {
  error.clear();
  std::error_code ec;
  const auto parent = std::filesystem::path(path).parent_path();
  if (!parent.empty()) {
    std::filesystem::create_directories(parent, ec);
    if (ec) {
      error = "failed to create input config directory: " + ec.message();
      return false;
    }
  }

  const std::string tmp = path + ".tmp";
  std::ofstream out(tmp, std::ios::trunc);
  if (!out) {
    error = "failed to open input config: " + tmp;
    return false;
  }
  out << BuildRetroArchInputConfig(device_name, bindings, joypad_index);
  out.close();
  if (!out) {
    error = "failed to write input config: " + tmp;
    return false;
  }
  std::filesystem::rename(tmp, path, ec);
  if (ec) {
    std::filesystem::remove(path, ec);
    ec.clear();
    std::filesystem::rename(tmp, path, ec);
  }
  if (ec) {
    error = "failed to replace input config: " + ec.message();
    return false;
  }
  return true;
}

}  // namespace gb::core
